// ---- Roles / principals -------------------------------------------------

export type StaffRole = "owner" | "manager" | "staff" | "kitchen";

export type ActorType = "user" | "pc" | "system" | "customer" | "superadmin_local";

export type EventSource = "online" | "offline" | "local";

// ---- PC -----------------------------------------------------------------

export type PcStatus = "online" | "offline" | "maintenance" | "disabled";

export type GamePlatform =
  | "steam"
  | "epic"
  | "riot"
  | "ea"
  | "battlenet"
  | "standalone";

export type InstallationState =
  | "not_installed"
  | "installing"
  | "ready"
  | "failed";

export type DeploymentJobStatus =
  | "queued"
  | "running"
  | "completed"
  | "failed"
  | "cancelled";

export type DeploymentTargetState =
  | "queued"
  | "downloading"
  | "verifying"
  | "installing"
  | "ready"
  | "paused"
  | "failed"
  | "offline";

// ---- Sessions ------------------------------------------------------------

export type SessionStatus =
  | "scheduled"
  | "active"
  | "paused"
  | "expired"
  | "ended"
  | "cancelled";

export type SessionOrigin = "admin" | "launcher" | "superadmin_offline";

export type SessionEventType =
  | "started"
  | "extended"
  | "ended"
  | "cancelled"
  | "paused"
  | "resumed"
  | "transferred"
  | "expired";

// ---- Commands ------------------------------------------------------------

export type CommandType =
  | "start_session"
  | "extend_session"
  | "end_session"
  | "lock"
  | "unlock"
  | "launch_game"
  | "restart"
  | "shutdown"
  | "refresh_config"
  | "enter_maintenance"
  | "request_health"
  | "deployment_control";

export type CommandStatus =
  | "pending"
  | "sent"
  | "applied"
  | "failed"
  | "expired";

/** Commands that require explicit confirmation from an authorized role. */
export const DANGEROUS_COMMANDS: readonly CommandType[] = [
  "end_session",
  "restart",
  "shutdown",
];

// ---- Orders / food -------------------------------------------------------

export type OrderStatus =
  | "placed"
  | "accepted"
  | "preparing"
  | "ready"
  | "delivered"
  | "completed"
  | "cancelled";

/** Legal transitions of the order state machine. */
export const ORDER_TRANSITIONS: Record<OrderStatus, OrderStatus[]> = {
  placed: ["accepted", "cancelled"],
  accepted: ["preparing", "cancelled"],
  preparing: ["ready", "cancelled"],
  ready: ["delivered"],
  delivered: ["completed"],
  completed: [],
  cancelled: [],
};

// ---- Offline sync ----------------------------------------------------------

/**
 * Offline event types generated by the PC agent outbox.
 * Keep in sync with docs/02-data-model.md §5 and docs/03-protocols.md §6.
 */
export type OfflineEventType =
  | "SESSION_STARTED"
  | "SESSION_EXTENDED"
  | "SESSION_ENDED"
  | "SESSION_CANCELLED"
  | "CUSTOMER_ASSIGNED"
  | "ORDER_CREATED"
  | "SUPERADMIN_ENTERED"
  | "SUPERADMIN_LOGIN_FAILED"
  | "TAMPER_SUSPECTED";

export type OfflineEventState = "accepted" | "duplicate" | "conflicted";

export type ConflictReason =
  | "DUPLICATE_SESSION"
  | "SESSION_ALREADY_ENDED"
  | "CLOCK_SKEW"
  | "UNKNOWN_EVENT_TYPE";

// ---- Payments ------------------------------------------------------------

export type PaymentMethod = "cash" | "upi" | "card" | "online" | "wallet";

export type PaymentStatus =
  | "pending"
  | "success"
  | "failed"
  | "refunded"
  | "partially_refunded";
